-- Skill requests: contractors can request a missing skill (lands pending until an admin approves it).
-- Also expands the curated skill vocabulary (idempotent — existing slugs are skipped) so the new searchable
-- picker has real coverage. The skill vocab stays the shared job↔contractor match key (Board listings + profiles).
ALTER TABLE "skill_category"
  ADD COLUMN "pending" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "requested_by" TEXT;
CREATE INDEX "skill_category_pending_idx" ON "skill_category" ("pending");

INSERT INTO "skill_category" ("id", "name", "slug", "active", "pending", "requested_by", "order") VALUES
  (gen_random_uuid(), 'Web Development', 'web-development', true, false, NULL, 10),
  (gen_random_uuid(), 'Frontend Development', 'frontend-development', true, false, NULL, 20),
  (gen_random_uuid(), 'Backend Development', 'backend-development', true, false, NULL, 30),
  (gen_random_uuid(), 'Full-Stack Development', 'full-stack-development', true, false, NULL, 40),
  (gen_random_uuid(), 'Mobile Development', 'mobile-development', true, false, NULL, 50),
  (gen_random_uuid(), 'iOS Development', 'ios-development', true, false, NULL, 60),
  (gen_random_uuid(), 'Android Development', 'android-development', true, false, NULL, 70),
  (gen_random_uuid(), 'React & Next.js', 'react-and-next-js', true, false, NULL, 80),
  (gen_random_uuid(), 'Vue & Nuxt', 'vue-and-nuxt', true, false, NULL, 90),
  (gen_random_uuid(), 'Node.js', 'node-js', true, false, NULL, 100),
  (gen_random_uuid(), 'Python Development', 'python-development', true, false, NULL, 110),
  (gen_random_uuid(), 'Ruby on Rails', 'ruby-on-rails', true, false, NULL, 120),
  (gen_random_uuid(), 'PHP & Laravel', 'php-and-laravel', true, false, NULL, 130),
  (gen_random_uuid(), '.NET Development', 'net-development', true, false, NULL, 140),
  (gen_random_uuid(), 'Java Development', 'java-development', true, false, NULL, 150),
  (gen_random_uuid(), 'Go Development', 'go-development', true, false, NULL, 160),
  (gen_random_uuid(), 'WordPress', 'wordpress', true, false, NULL, 170),
  (gen_random_uuid(), 'Shopify Development', 'shopify-development', true, false, NULL, 180),
  (gen_random_uuid(), 'Webflow', 'webflow', true, false, NULL, 190),
  (gen_random_uuid(), 'API Development', 'api-development', true, false, NULL, 200),
  (gen_random_uuid(), 'E-commerce Development', 'e-commerce-development', true, false, NULL, 210),
  (gen_random_uuid(), 'Game Development', 'game-development', true, false, NULL, 220),
  (gen_random_uuid(), 'Blockchain & Web3', 'blockchain-and-web3', true, false, NULL, 230),
  (gen_random_uuid(), 'Browser Extensions', 'browser-extensions', true, false, NULL, 240),
  (gen_random_uuid(), 'No-Code & Low-Code', 'no-code-and-low-code', true, false, NULL, 250),
  (gen_random_uuid(), 'Embedded & IoT', 'embedded-and-iot', true, false, NULL, 260),
  (gen_random_uuid(), 'UI/UX Design', 'ui-ux-design', true, false, NULL, 270),
  (gen_random_uuid(), 'Product Design', 'product-design', true, false, NULL, 280),
  (gen_random_uuid(), 'Web Design', 'web-design', true, false, NULL, 290),
  (gen_random_uuid(), 'Brand & Graphic Design', 'brand-and-graphic-design', true, false, NULL, 300),
  (gen_random_uuid(), 'Logo Design', 'logo-design', true, false, NULL, 310),
  (gen_random_uuid(), 'Illustration', 'illustration', true, false, NULL, 320),
  (gen_random_uuid(), 'Design Systems', 'design-systems', true, false, NULL, 330),
  (gen_random_uuid(), 'Motion Design', 'motion-design', true, false, NULL, 340),
  (gen_random_uuid(), '3D Design', '3d-design', true, false, NULL, 350),
  (gen_random_uuid(), 'Print Design', 'print-design', true, false, NULL, 360),
  (gen_random_uuid(), 'Content & Copywriting', 'content-and-copywriting', true, false, NULL, 370),
  (gen_random_uuid(), 'Technical Writing', 'technical-writing', true, false, NULL, 380),
  (gen_random_uuid(), 'Content Strategy', 'content-strategy', true, false, NULL, 390),
  (gen_random_uuid(), 'SEO & Growth', 'seo-and-growth', true, false, NULL, 400),
  (gen_random_uuid(), 'Growth Marketing', 'growth-marketing', true, false, NULL, 410),
  (gen_random_uuid(), 'Paid Media', 'paid-media', true, false, NULL, 420),
  (gen_random_uuid(), 'Social Media Management', 'social-media-management', true, false, NULL, 430),
  (gen_random_uuid(), 'Email Marketing', 'email-marketing', true, false, NULL, 440),
  (gen_random_uuid(), 'Marketing Automation', 'marketing-automation', true, false, NULL, 450),
  (gen_random_uuid(), 'PR & Communications', 'pr-and-communications', true, false, NULL, 460),
  (gen_random_uuid(), 'Brand Strategy', 'brand-strategy', true, false, NULL, 470),
  (gen_random_uuid(), 'Conversion Optimization', 'conversion-optimization', true, false, NULL, 480),
  (gen_random_uuid(), 'Data & Analytics', 'data-and-analytics', true, false, NULL, 490),
  (gen_random_uuid(), 'Data Engineering', 'data-engineering', true, false, NULL, 500),
  (gen_random_uuid(), 'Data Science', 'data-science', true, false, NULL, 510),
  (gen_random_uuid(), 'Machine Learning', 'machine-learning', true, false, NULL, 520),
  (gen_random_uuid(), 'AI & Automation', 'ai-and-automation', true, false, NULL, 530),
  (gen_random_uuid(), 'AI Engineering & LLMs', 'ai-engineering-and-llms', true, false, NULL, 540),
  (gen_random_uuid(), 'Business Intelligence', 'business-intelligence', true, false, NULL, 550),
  (gen_random_uuid(), 'Database Administration', 'database-administration', true, false, NULL, 560),
  (gen_random_uuid(), 'DevOps & Infrastructure', 'devops-and-infrastructure', true, false, NULL, 570),
  (gen_random_uuid(), 'Cloud Architecture', 'cloud-architecture', true, false, NULL, 580),
  (gen_random_uuid(), 'Site Reliability (SRE)', 'site-reliability-sre', true, false, NULL, 590),
  (gen_random_uuid(), 'Security & Cybersecurity', 'security-and-cybersecurity', true, false, NULL, 600),
  (gen_random_uuid(), 'QA & Testing', 'qa-and-testing', true, false, NULL, 610),
  (gen_random_uuid(), 'Systems Administration', 'systems-administration', true, false, NULL, 620),
  (gen_random_uuid(), 'Video & Motion', 'video-and-motion', true, false, NULL, 630),
  (gen_random_uuid(), 'Video Editing', 'video-editing', true, false, NULL, 640),
  (gen_random_uuid(), 'Animation', 'animation', true, false, NULL, 650),
  (gen_random_uuid(), 'Audio Production', 'audio-production', true, false, NULL, 660),
  (gen_random_uuid(), 'Photography', 'photography', true, false, NULL, 670),
  (gen_random_uuid(), 'Project Management', 'project-management', true, false, NULL, 680),
  (gen_random_uuid(), 'Product Management', 'product-management', true, false, NULL, 690),
  (gen_random_uuid(), 'Business Analysis', 'business-analysis', true, false, NULL, 700),
  (gen_random_uuid(), 'Operations & RevOps', 'operations-and-revops', true, false, NULL, 710),
  (gen_random_uuid(), 'Sales & Sales Engineering', 'sales-and-sales-engineering', true, false, NULL, 720),
  (gen_random_uuid(), 'Customer Success', 'customer-success', true, false, NULL, 730),
  (gen_random_uuid(), 'Bookkeeping & Finance', 'bookkeeping-and-finance', true, false, NULL, 740),
  (gen_random_uuid(), 'Consulting & Strategy', 'consulting-and-strategy', true, false, NULL, 750),
  (gen_random_uuid(), 'Virtual Assistant', 'virtual-assistant', true, false, NULL, 760),
  (gen_random_uuid(), 'HubSpot', 'hubspot', true, false, NULL, 770),
  (gen_random_uuid(), 'Salesforce', 'salesforce', true, false, NULL, 780),
  (gen_random_uuid(), 'CRM Implementation', 'crm-implementation', true, false, NULL, 790),
  (gen_random_uuid(), 'Systems Integration', 'systems-integration', true, false, NULL, 800),
  (gen_random_uuid(), 'Workflow Automation', 'workflow-automation', true, false, NULL, 810)
ON CONFLICT DO NOTHING;
